apiVersion: v2
name: tekton-operator
description: A Helm chart to deploy the Tekton Operator and its CRDs
type: application
version: 0.67.0
# corresponds to the version of tekton-operator
# https://github.com/tektoncd/operator/releases
appVersion: "v0.67.0"
maintainers:
  - name: Jack Henschel
    email: jack.henschel@cern.ch
sources:
  - https://github.com/tektoncd/operator
