{{- if (and (not .Values.openshift.enabled) .Values.installCRDs) -}}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.64.0
    version: v0.64.0
  name: tektonchains.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonChain
    listKind: TektonChainList
    plural: tektonchains
    singular: tektonchain
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the TektonChains API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.64.0
    version: v0.64.0
  name: tektonconfigs.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonConfig
    listKind: TektonConfigList
    plural: tektonconfigs
    singular: tektonconfig
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektonconfigs API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.64.0
    version: v0.64.0
  name: tektondashboards.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonDashboard
    listKind: TektonDashboardList
    plural: tektondashboards
    singular: tektondashboard
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektondashboards API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.64.0
    version: v0.64.0
  name: tektonhubs.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonHub
    listKind: TektonHubList
    plural: tektonhubs
    singular: tektonhub
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
        - jsonPath: .status.apiUrl
          name: ApiUrl
          type: string
        - jsonPath: .status.uiUrl
          name: UiUrl
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektonhubs API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.64.0
    version: v0.64.0
  name: tektoninstallersets.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonInstallerSet
    listKind: TektonInstallerSetList
    plural: tektoninstallersets
    singular: tektoninstallerset
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektoninstallerset API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.64.0
    version: v0.64.0
  name: tektonpipelines.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonPipeline
    listKind: TektonPipelineList
    plural: tektonpipelines
    singular: tektonpipeline
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektonpipelines API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.64.0
    version: v0.64.0
  name: tektonresults.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonResult
    listKind: TektonResultList
    plural: tektonresults
    singular: tektonresult
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektonresults API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/  api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of TektonResult
              properties:
                targetNamespace:
                  description: namespace where tekton results will be installed
                  type: string
              type: object
            status:
              description: Status defines the observed state of TektonResult
              properties:
                conditions:
                  description: The latest available observations of a resource's current state.
                  items:
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant).
                        type: string
                      message:
                        description: A human readable message indicating details about the transition.
                        type: string
                      reason:
                        description: The reason for the condition's last transition.
                        type: string
                      severity:
                        description: Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error.
                        type: string
                      status:
                        description: Status of the condition, one of True, False, Unknown.
                        type: string
                      type:
                        description: Type of condition.
                        type: string
                    required:
                      - type
                      - status
                    type: object
                  type: array
                manifests:
                  description: The list of results manifests, which have been installed by the operator
                  items:
                    type: string
                  type: array
                observedGeneration:
                  description: The generation last processed by the controller
                  type: integer
                version:
                  description: The version of the installed release
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.64.0
    version: v0.64.0
  name: tektontriggers.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonTrigger
    listKind: TektonTriggerList
    plural: tektontriggers
    singular: tektontrigger
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektontriggers API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
{{- end -}}
