{{- if not .Values.webhook.certSecret.useExistingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webhook.certSecret.name | default (include "tekton-operator.fullname" .) }}-webhook-certs
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
{{- end }}
