resources:
- addon/operator_v1alpha1_addon_cr.yaml
- config/all/operator_v1alpha1_config_cr.yaml
- pipeline/operator_v1alpha1_pipeline_cr.yaml
- trigger/operator_v1alpha1_trigger_cr.yaml
- installerset/operator_v1alpha1_installerset_cr.yaml
- chain/operator_v1alpha1_chain_cr.yaml
- hub/operator_v1alpha1_hub_cr.yaml
- pipelinesascode/operator_v1alpha1_openshiftpipelinesascode_cr.yaml
- result/operator_v1alpha1_result_cr.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
