# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-pipelines-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openshift-pipelines-operator
      app: openshift-pipelines-operator
  template:
    metadata:
      labels:
        name: openshift-pipelines-operator
        app: openshift-pipelines-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: openshift-pipelines-operator
      containers:
      - name: openshift-pipelines-operator-lifecycle  # all reconcilers except tektoninstallerset reconciler
        image: ko://github.com/tektoncd/operator/cmd/openshift/operator
        args:
        - "-controllers"
        - "tektonconfig,tektonpipeline,tektontrigger,tektonhub,tektonchain,tektonaddon"
        - "-unique-process-name"
        - "tekton-operator-lifecycle"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PLATFORM
          value: "openshift"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: redhat-openshift-pipelines-operator
        - name: IMAGE_PIPELINES_PROXY
          value: ko://github.com/tektoncd/operator/cmd/openshift/proxy-webhook
        - name: IMAGE_JOB_PRUNER_TKN
          value: gcr.io/tekton-releases/dogfooding/tkn@sha256:025de221fb059ca24a3b2d988889ea34bce48dc76c0cf0d6b4499edb8c21325f
        - name: METRICS_DOMAIN
          value: tekton.dev/operator
        - name: VERSION
          value: "devel"
        - name: AUTOINSTALL_COMPONENTS
          valueFrom:
            configMapKeyRef:
              name: tekton-config-defaults
              key: AUTOINSTALL_COMPONENTS
        - name: DEFAULT_TARGET_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: tekton-config-defaults
              key: DEFAULT_TARGET_NAMESPACE
        - name: CONFIG_OBSERVABILITY_NAME
          value: tekton-config-observability
        - name: IMAGE_HUB_TEKTON_HUB_DB
          value: registry.redhat.io/rhel8/postgresql-13@sha256:9fd7af383b4070866b7ae013f19e9c672de7dff14e1661fd24d763277ac1cfd3
        - name: IMAGE_ADDONS_PARAM_BUILDER_IMAGE
          value: registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
        - name: IMAGE_ADDONS_PARAM_KN_IMAGE
          value: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:356a55c587203ae8205fd177f39cd1a6dbd8962c4dffcbc576d74009b668d256
        - name: IMAGE_ADDONS_MVN_SETTINGS
          value: registry.redhat.io/ubi8/ubi-minimal@sha256:c7b45019f4db32e536e69e102c4028b66bf5cde173cfff4ffd3281ccf7bb3863
        - name: IMAGE_ADDONS_SKOPEO_COPY
          value: registry.redhat.io/rhel8/skopeo@sha256:5a83242e519a2b6e3387c3567ba799a94604be1b7d2e3cd134a631b9827c9762
        - name: IMAGE_ADDONS_GENERATE
          value: registry.redhat.io/ocp-tools-4-tech-preview/source-to-image-rhel8@sha256:98d8cb3a255641ca6a1bce854e5e2460c20de9fb9b28e3cc67eb459f122873dd
        - name: IMAGE_ADDONS_GEN_ENV_FILE
          value: registry.redhat.io/ocp-tools-4-tech-preview/source-to-image-rhel8@sha256:98d8cb3a255641ca6a1bce854e5e2460c20de9fb9b28e3cc67eb459f122873dd
      - name: openshift-pipelines-operator-cluster-operations  # tektoninstallerset reconciler
        image: ko://github.com/tektoncd/operator/cmd/openshift/operator
        args:
        - "-controllers"
        - "tektoninstallerset"
        - "-unique-process-name"
        - "tekton-operator-cluster-operations"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        env:
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: redhat-openshift-pipelines-operator
          - name: PROFILING_PORT
            value: "9009"
          - name: VERSION
            value: "devel"
          - name: METRICS_DOMAIN
            value: tekton.dev/operator
