apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: openshift-pipelines-operator-prometheus-k8s-read-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-pipelines-operator-read
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
