apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    operator.tekton.dev/release: devel
    version: devel
  name: tektonhubs.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonHub
    listKind: TektonHubList
    plural: tektonhubs
    singular: tektonhub
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.version
      name: Version
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].reason
      name: Reason
      type: string
    - jsonPath: .status.apiUrl
      name: ApiUrl
      type: string
    - jsonPath: .status.uiUrl
      name: UiUrl
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Schema for the tektonhubs API
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
