apiVersion: v1
data:
  AUTOINSTALL_COMPONENTS: "true"
  DEFAULT_TARGET_NAMESPACE: openshift-pipelines
kind: ConfigMap
metadata:
  labels:
    operator.tekton.dev/release: devel
  name: tekton-config-defaults
