apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tekton-pipelines-controller
    version: v0.78.0
  name: tekton-operator
spec:
  ports:
  - name: http-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: tekton-operator
    name: tekton-operator
status:
  loadBalancer: {}
