apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tekton-operator
    name: tekton-operator-webhook
    operator.tekton.dev/release: v0.75.0
    version: v0.75.0
  name: tekton-operator-webhook
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    app: tekton-operator
    name: tekton-operator-webhook
status:
  loadBalancer: {}
