apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: config.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: Config
    listKind: ConfigList
    plural: config
    singular: config
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            targetNamespace:
              description: namespace where OpenShift pipelines will be installed
              type: string
          required:
          - targetNamespace
          type: object
        status:
          properties:
            conditions:
              description: installation status sorted in reverse chronological order
              items:
                properties:
                  code:
                    description: Code indicates the status of installation of pipeline resources.
                    type: string
                  details:
                    description: Additional details about the Code
                    type: string
                  version:
                    description: The version of tekton pipelines
                    type: string
                required:
                - code
                - version
                type: object
              type: array
          type: object
  additionalPrinterColumns:
  - JSONPath: ".status.conditions[0].code"
    name: status
    type: string
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
