{{- if (and .Values.openshift.enabled .Values.installCRDs) -}}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: manualapprovalgates.operator.tekton.dev
  labels:
    version: v0.78.1
    operator.tekton.dev/release: v0.78.1
spec:
  group: operator.tekton.dev
  names:
    kind: ManualApprovalGate
    listKind: ManualApprovalGateList
    plural: manualapprovalgates
    singular: manualapprovalgate
    shortNames:
      - mag
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: ".status.conditions[?(@.type==\"Ready\")].message"
          name: Reason
          type: string
      schema:
        openAPIV3Schema:
          type: object
          description: Schema for the ManualApprovalGate API
          x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.78.1
    version: v0.78.1
  name: openshiftpipelinesascodes.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: OpenShiftPipelinesAsCode
    listKind: OpenShiftPipelinesAsCodeList
    plural: openshiftpipelinesascodes
    shortNames:
      - opac
      - pac
    singular: openshiftpipelinesascode
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the OpenShiftPipelinesAsCode API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.78.1
    version: v0.78.1
  name: tektonaddons.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonAddon
    listKind: TektonAddonList
    plural: tektonaddons
    singular: tektonaddon
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektonaddons API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.78.1
    version: v0.78.1
  name: tektonchains.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonChain
    listKind: TektonChainList
    plural: tektonchains
    singular: tektonchain
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the TektonChains API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.78.1
    version: v0.78.1
  name: tektonconfigs.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonConfig
    listKind: TektonConfigList
    plural: tektonconfigs
    singular: tektonconfig
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektonconfigs API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.78.1
    version: v0.78.1
  name: tektonhubs.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonHub
    listKind: TektonHubList
    plural: tektonhubs
    singular: tektonhub
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
        - jsonPath: .status.apiUrl
          name: ApiUrl
          type: string
        - jsonPath: .status.uiUrl
          name: UiUrl
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektonhubs API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.78.1
    version: v0.78.1
  name: tektoninstallersets.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonInstallerSet
    listKind: TektonInstallerSetList
    plural: tektoninstallersets
    singular: tektoninstallerset
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektoninstallerset API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.78.1
    version: v0.78.1
  name: tektonpipelines.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonPipeline
    listKind: TektonPipelineList
    plural: tektonpipelines
    singular: tektonpipeline
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektonpipelines API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.78.1
    version: v0.78.1
  name: tektonresults.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonResult
    listKind: TektonResultList
    plural: tektonresults
    singular: tektonresult
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the TektonResults API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.78.1
    version: v0.78.1
  name: tektontriggers.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonTrigger
    listKind: TektonTriggerList
    plural: tektontriggers
    singular: tektontrigger
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektontriggers API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: v0.78.1
    version: v0.78.1
  name: tektonpruners.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonPruner
    listKind: TektonPrunerList
    plural: tektonpruners
    singular: tektonpruner
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].message
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the TektonPruner API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
{{- end -}}
