apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tekton-operator
  template:
    metadata:
      labels:
        name: tekton-operator
    spec:
      serviceAccountName: tekton-operator
      containers:
        - name: tekton-operator
          image: github.com/tektoncd/operator/cmd/manager
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tekton-operator"
          args:
            - --no-auto-install=true
