platform: "openshift"
operator-packagename: "openshift-pipelines-operator-rh"
image-substitutions:
- image: registry.redhat.io/openshift-pipelines/pipelines-rhel8-operator@
  replaceLocations:
    containerTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
- image: registry.redhat.io/openshift-pipelines/pipelines-rhel8-operator@
  replaceLocations:
    containerTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-cluster-operations
- image: registry.redhat.io/openshift-pipelines/pipelines-operator-proxy-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_PROXY
- image: registry.redhat.io/openshift-pipelines/pipelines-controller-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-webhook-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_WEBHOOK
- image: registry.redhat.io/openshift-pipelines/pipelines-resolvers-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      # the container name for resolvers controller is "controller" :)
      - IMAGE_PIPELINES_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-entrypoint-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
# add git-init image from 1.10.5 release
- image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:9b14f52b21d29d8d83ea4c0e78623debc954f1a732d2be6d1a7269fbba23b1a4
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__GIT_IMAGE
      - IMAGE_ADDONS_PARAM_GITINITIMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-workingdirinit-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-nop-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__NOP_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-entrypoint-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__SHELL_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-controller-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-webhook-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_WEBHOOK
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-core-interceptors-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-eventlistenersink-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_ARG__EL_IMAGE
- image: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:bf6cf2e87fb19f7aa9a490b83c16af69834c0721220a643710a1b077959e91ca
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_PARAM_KN_IMAGE
- image: registry.redhat.io/rhel8/skopeo@sha256:91f6ffc3be778ebeb59a0da528f93da5a0332b61d1e689ffdbaf159d25cabaeb
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_SKOPEO_COPY
- image: registry.redhat.io/rhel8/buildah@sha256:55f5c7d88c77e1ab5a2ab8e877172b2b66cb196e21f10dc45148470d0ee8bbae
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_PARAM_BUILDER_IMAGE
- image: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_GENERATE
      - IMAGE_ADDONS_GEN_ENV_FILE

- image: registry.redhat.io/ubi8/ubi-minimal@sha256:b93deceb59a58588d5b16429fc47f98920f84740a1f2ed6454e33275f0701b59
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_ADDONS_MVN_SETTINGS
- image: registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_JOB_PRUNER_TKN
      - IMAGE_ADDONS_PARAM_TKN_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_TKN_CLI_SERVE
- image: registry.redhat.io/openshift-pipelines/pipelines-operator-webhook-rhel8@
  replaceLocations:
    containerTargets:
    - deploymentName: tekton-operator-webhook
      containerName: tekton-operator-webhook
- image: registry.redhat.io/openshift-pipelines/pipelines-chains-controller-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
- image: registry.redhat.io/rhel8/postgresql-13@sha256:8f837badac11de8a7866e137b7763bbd10418b935e82868dddf09280683c2455
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_DB
          - IMAGE_RESULTS_POSTGRES
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-db-migration-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-api-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_API
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-ui-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_UI
- image: registry.redhat.io/openshift-pipelines/pipelines-pipelines-as-code-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_PAC_PAC_CONTROLLER
          - IMAGE_PAC_PAC_WEBHOOK
          - IMAGE_PAC_PAC_WATCHER
- image: registry.redhat.io/openshift-pipelines/pipelines-results-watcher-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_RESULTS_WATCHER
- image: registry.redhat.io/openshift-pipelines/pipelines-results-api-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_RESULTS_API

- image: registry.redhat.io/ubi8/openjdk-17@sha256:af305e087061cbaa4107ce0b304a1ef987f6b54bae3f75bfd529cfd084cba9b5
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_ADDONS_PARAM_MAVEN_IMAGE

# add third party images which are not replaced by operator
# but pulled directly by tasks here
defaultRelatedImages: []
#  - image: "" ##<imagename>:<tag> or <imagename>@<sha>
#    name: "" # ENV key name value
