platform: "openshift"
operator-packagename: "openshift-pipelines-operator-rh"
image-substitutions:
- image: registry.redhat.io/openshift-pipelines/pipelines-rhel8-operator@
  replaceLocations:
    containerTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
- image: registry.redhat.io/openshift-pipelines/pipelines-rhel8-operator@
  replaceLocations:
    containerTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-cluster-operations
- image: registry.redhat.io/openshift-pipelines/pipelines-operator-proxy-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_PROXY
- image: registry.redhat.io/openshift-pipelines/pipelines-controller-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-webhook-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_WEBHOOK
- image: registry.redhat.io/openshift-pipelines/pipelines-resolvers-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      # the container name for resolvers controller is "controller" :)
      - IMAGE_PIPELINES_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-events-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-entrypoint-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__GIT_IMAGE
      - IMAGE_ADDONS_PARAM_GITINITIMAGE
      - IMAGE_ADDONS_GIT_RUN
      - IMAGE_ADDONS_REPORT
      - IMAGE_ADDONS_GIT_CLONE
- image: registry.redhat.io/openshift-pipelines/pipelines-workingdirinit-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-nop-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__NOP_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-entrypoint-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__SHELL_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-controller-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-webhook-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_WEBHOOK
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-core-interceptors-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-eventlistenersink-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_ARG__EL_IMAGE
- image: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:bf6cf2e87fb19f7aa9a490b83c16af69834c0721220a643710a1b077959e91ca
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_PARAM_KN_IMAGE
      - IMAGE_ADDONS_KN
- image: registry.redhat.io/rhel8/skopeo@sha256:29465586e92ed04d2878dcdeda2d508c7e8e7539762e10296b52d631929960aa
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_SKOPEO_COPY
      - IMAGE_ADDONS_SKOPEO_RESULTS
- image: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_PARAM_BUILDER_IMAGE
      - IMAGE_ADDONS_BUILD
      - IMAGE_ADDONS_S2I_BUILD
- image: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_GENERATE
      - IMAGE_ADDONS_GEN_ENV_FILE
      - IMAGE_ADDONS_S2I_GENERATE
- image: registry.redhat.io/ubi8/ubi-minimal@sha256:f729a7f5685ea823e87ffd68aff988f2b8ff8d52126ade4e6de7c68088f28ebd
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_ADDONS_MVN_SETTINGS
          - IMAGE_ADDONS_LOAD_SCRIPTS
          - IMAGE_ADDONS_MAVEN_GENERATE
          - IMAGE_ADDONS_PREPARE
- image: registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_JOB_PRUNER_TKN
      - IMAGE_ADDONS_PARAM_TKN_IMAGE
      - IMAGE_ADDONS_TKN
- image: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_TKN_CLI_SERVE
- image: registry.redhat.io/openshift-pipelines/pipelines-operator-webhook-rhel8@
  replaceLocations:
    containerTargets:
    - deploymentName: tekton-operator-webhook
      containerName: tekton-operator-webhook
- image: registry.redhat.io/openshift-pipelines/pipelines-chains-controller-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
- image: registry.redhat.io/rhel8/postgresql-13@sha256:a92a579f1aef66ac188d24fd489c456a1a3e311d95dcce652da6b81e28fbf725
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_DB
          - IMAGE_RESULTS_POSTGRES
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-db-migration-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-api-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_API
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-ui-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_UI
- image: registry.redhat.io/openshift-pipelines/pipelines-manual-approval-gate-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
          - IMAGE_MAG_MANUAL_APPROVAL
- image: registry.redhat.io/openshift-pipelines/pipelines-pipelines-as-code-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_PAC_PAC_CONTROLLER
          - IMAGE_PAC_PAC_WEBHOOK
          - IMAGE_PAC_PAC_WATCHER
- image: registry.redhat.io/openshift-pipelines/pipelines-results-watcher-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_RESULTS_WATCHER
- image: registry.redhat.io/openshift-pipelines/pipelines-results-api-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_RESULTS_API
- image: registry.redhat.io/openshift-pipelines/pipelines-results-retention-policy-agent-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_RESULTS_RETENTION_POLICY_AGENT
- image: registry.redhat.io/ubi8/openjdk-17@sha256:e8cc2e476282b75d89c73057bfa713db22d72bdb2808d62d981a84c33beb2575
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_ADDONS_PARAM_MAVEN_IMAGE
          - IMAGE_ADDONS_MAVEN_GOALS

# pipelines console plugin image
- image: registry.redhat.io/openshift-pipelines/pipelines-console-plugin-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_PIPELINES_CONSOLE_PLUGIN

# add third party images which are not replaced by operator
# but pulled directly by tasks here
defaultRelatedImages: []
#  - image: "" ##<imagename>:<tag> or <imagename>@<sha>
#    name: "" # ENV key name value
