platform: "openshift"
operator-packagename: "openshift-pipelines-operator-rh"
image-substitutions:
- image: registry.redhat.io/openshift-pipelines/pipelines-rhel8-operator@
  replaceLocations:
    containerTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
- image: registry.redhat.io/openshift-pipelines/pipelines-operator-proxy-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_PIPELINES_PROXY
- image: registry.redhat.io/openshift-pipelines/pipelines-controller-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-webhook-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_PIPELINES_WEBHOOK
- image: registry.redhat.io/openshift-pipelines/pipelines-entrypoint-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_PIPELINES_ARG__GIT_IMAGE
      - IMAGE_ADDONS_PARAM_GITINITIMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-imagedigestexporter-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_PIPELINES_ARG__IMAGEDIGEST_EXPORTER_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-kubeconfigwriter-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_PIPELINES_ARG__KUBECONFIG_WRITER_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-workingdirinit-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator
        envKeys:
          - IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-pullrequest-init-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_PIPELINES_ARG__PR_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-nop-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_PIPELINES_ARG__NOP_IMAGE
- image: registry.access.redhat.com/ubi8/ubi-minimal@sha256:cf1c63e3247e4074ee3549a064b8798a1a2513ad57dd79c9edb979836355b469
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_PIPELINES_ARG__SHELL_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-controller-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-webhook-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_TRIGGERS_WEBHOOK
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-core-interceptors-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-eventlistenersink-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_TRIGGERS_ARG__EL_IMAGE
- image: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:b8b992e36f76d80b1daeed0532adf94b1ce570a6aaef1dbcc2a28c666f8cd296
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_ADDONS_PARAM_KN_IMAGE
- image: registry.redhat.io/rhel8/skopeo@sha256:a458abaee565344e8c31468bb5bec26bdc622c559678ab73b07ee4998de68bd0
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_ADDONS_SKOPEO_COPY
- image: registry.redhat.io/rhel8/buildah@sha256:31f84b19a0774be7cfad751be38fc97f5e86cefd26e0abaec8047ddc650b00bf
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_ADDONS_PARAM_BUILDER_IMAGE
- image: registry.redhat.io/ocp-tools-4-tech-preview/source-to-image-rhel8@sha256:98d8cb3a255641ca6a1bce854e5e2460c20de9fb9b28e3cc67eb459f122873dd
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_ADDONS_GENERATE
- image: registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_JOB_PRUNER_TKN
      - IMAGE_ADDONS_PARAM_TKN_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator
      envKeys:
      - IMAGE_ADDONS_TKN_CLI_SERVE
- image: registry.redhat.io/openshift-pipelines/pipelines-operator-webhook-rhel8@
  replaceLocations:
    containerTargets:
    - deploymentName: tekton-operator-webhook
      containerName: tekton-operator-webhook
- image: registry.redhat.io/openshift-pipelines/pipelines-chains-controller-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator
        envKeys:
          - IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
- image: registry.redhat.io/rhel8/postgresql-13@sha256:6032adb3eac903ee8aa61f296ca9aaa57f5709e5673504b609222e042823f195
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_DB
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-db-migration-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-api-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_API
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-ui-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_UI
- image: registry.redhat.io/openshift-pipelines/pipelines-pipelines-as-code-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator
        envKeys:
          - IMAGE_PAC_TRIGGERTEMPLATE_APPLY_AND_LAUNCH

# add third party images which are not replaced by operator
# but pulled directly by tasks here
defaultRelatedImages:
- image: registry.redhat.io/rhel8/buildah@sha256:31f84b19a0774be7cfad751be38fc97f5e86cefd26e0abaec8047ddc650b00bf
  name: IMAGE_ADDONS_PARAM_BUILDER_IMAGE
- image: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:b8b992e36f76d80b1daeed0532adf94b1ce570a6aaef1dbcc2a28c666f8cd296
  name: IMAGE_ADDONS_PARAM_KN_IMAGE
- image: registry.redhat.io/rhel8/skopeo@sha256:a458abaee565344e8c31468bb5bec26bdc622c559678ab73b07ee4998de68bd0
  name: IMAGE_ADDONS_SKOPEO_COPY
- image: registry.redhat.io/ocp-tools-4-tech-preview/source-to-image-rhel8@sha256:98d8cb3a255641ca6a1bce854e5e2460c20de9fb9b28e3cc67eb459f122873dd
  name: IMAGE_ADDONS_GENERATE
#- image: "" ##<imagename>:<tag> or <imagename>@<sha>
#  name: "" # ENV key name value
