platform: "openshift"
operator-packagename: "openshift-pipelines-operator-rh"
image-substitutions:
- image: registry.redhat.io/openshift-pipelines/pipelines-rhel8-operator@
  replaceLocations:
    containerTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
- image: registry.redhat.io/openshift-pipelines/pipelines-rhel8-operator@
  replaceLocations:
    containerTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-cluster-operations
- image: registry.redhat.io/openshift-pipelines/pipelines-operator-proxy-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_PROXY
- image: registry.redhat.io/openshift-pipelines/pipelines-controller-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-webhook-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_WEBHOOK
- image: registry.redhat.io/openshift-pipelines/pipelines-resolvers-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      # the container name for resolvers controller is "controller" :)
      - IMAGE_PIPELINES_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-entrypoint-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__GIT_IMAGE
      - IMAGE_ADDONS_PARAM_GITINITIMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-imagedigestexporter-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__IMAGEDIGEST_EXPORTER_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-kubeconfigwriter-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__KUBECONFIG_WRITER_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-workingdirinit-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-pullrequest-init-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__PR_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-nop-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__NOP_IMAGE
- image: registry.redhat.io/ubi8/ubi-minimal@sha256:c7b45019f4db32e536e69e102c4028b66bf5cde173cfff4ffd3281ccf7bb3863
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_PIPELINES_ARG__SHELL_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-controller-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-webhook-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_WEBHOOK
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-core-interceptors-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
- image: registry.redhat.io/openshift-pipelines/pipelines-triggers-eventlistenersink-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_TRIGGERS_ARG__EL_IMAGE
- image: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:356a55c587203ae8205fd177f39cd1a6dbd8962c4dffcbc576d74009b668d256
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_PARAM_KN_IMAGE
- image: registry.redhat.io/rhel8/skopeo@sha256:5a83242e519a2b6e3387c3567ba799a94604be1b7d2e3cd134a631b9827c9762
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_SKOPEO_COPY
- image: registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_PARAM_BUILDER_IMAGE
- image: registry.redhat.io/ocp-tools-4-tech-preview/source-to-image-rhel8@sha256:98d8cb3a255641ca6a1bce854e5e2460c20de9fb9b28e3cc67eb459f122873dd
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_GENERATE
      - IMAGE_ADDONS_GEN_ENV_FILE

- image: registry.redhat.io/ubi8/ubi-minimal@sha256:c7b45019f4db32e536e69e102c4028b66bf5cde173cfff4ffd3281ccf7bb3863
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_ADDONS_MVN_SETTINGS
- image: registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_JOB_PRUNER_TKN
      - IMAGE_ADDONS_PARAM_TKN_IMAGE
- image: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@
  replaceLocations:
    envTargets:
    - deploymentName: openshift-pipelines-operator
      containerName: openshift-pipelines-operator-lifecycle
      envKeys:
      - IMAGE_ADDONS_TKN_CLI_SERVE
- image: registry.redhat.io/openshift-pipelines/pipelines-operator-webhook-rhel8@
  replaceLocations:
    containerTargets:
    - deploymentName: tekton-operator-webhook
      containerName: tekton-operator-webhook
- image: registry.redhat.io/openshift-pipelines/pipelines-chains-controller-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
- image: registry.redhat.io/rhel8/postgresql-13@sha256:9fd7af383b4070866b7ae013f19e9c672de7dff14e1661fd24d763277ac1cfd3
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_DB
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-db-migration-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-api-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_API
- image: registry.redhat.io/openshift-pipelines/pipelines-hub-ui-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_HUB_TEKTON_HUB_UI
- image: registry.redhat.io/openshift-pipelines/pipelines-pipelines-as-code-rhel8@
  replaceLocations:
    envTargets:
      - deploymentName: openshift-pipelines-operator
        containerName: openshift-pipelines-operator-lifecycle
        envKeys:
          - IMAGE_PAC_PAC_CONTROLLER
          - IMAGE_PAC_PAC_WEBHOOK
          - IMAGE_PAC_PAC_WATCHER

# add third party images which are not replaced by operator
# but pulled directly by tasks here
defaultRelatedImages: []
#  - image: "" ##<imagename>:<tag> or <imagename>@<sha>
#    name: "" # ENV key name value
