apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dashboard/operator_v1alpha1_dashboard_cr.yaml
- result/operator_v1alpha1_result_cr.yaml
- pipeline/operator_v1alpha1_pipeline_cr.yaml
- trigger/operator_v1alpha1_trigger_cr.yaml
- config/all/operator_v1alpha1_config_cr.yaml
- installerset/operator_v1alpha1_installerset_cr.yaml
- chain/operator_v1alpha1_chain_cr.yaml
- hub/operator_v1alpha1_hub_cr.yaml
- manualapprovalgate/operator_v1alpha1_manualapprovalgate_cr.yaml
- pruner/operator_v1alpha1_pruner_cr.yaml
