apiVersion: v2
name: tekton-operator
description: A Helm chart to deploy the Tekton Operator and its CRDs
type: application
version: "devel"
# corresponds to the version of tekton-operator
# https://github.com/tektoncd/operator/releases
appVersion: "devel"
maintainers:
  - name: Jack Henschel
    email: jack.henschel@cern.ch
sources:
  - https://github.com/tektoncd/operator
