name: Bump components.yaml on release branches

on:  # yamllint disable-line rule:truthy
  workflow_dispatch: {}
  schedule:
  # Run this every week day at 2AM
  - cron: '0 2 * * 1-5'

jobs:
  build-release-matrix:
    runs-on: ubuntu-latest
    steps:
    - id: set-matrix
      run: |
        git ls-remote --heads https://github.com/tektoncd/operator 'release-*' | grep -v 'v0.2\.*\|v0.5\.*\|v0.60\|v0.61' | awk '{ print $2 }' | cut -d/ -f3- | jq -cRs 'split("\n")[:-1]'
        echo "branches=$(git ls-remote --heads https://github.com/tektoncd/operator 'release-*' | grep -v 'v0.2\.*\|v0.5\.*\|v0.60\|v0.61' | awk '{ print $2 }' | cut -d/ -f3- | jq -cRs 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    outputs:
      branches: ${{ steps.set-matrix.outputs.branches }}
  bump-payloads:
    needs: build-release-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.build-release-matrix.outputs.branches) }}
        # branch: [release-v0.62.x, release-v0.63.x]
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: 1.18.x
    - uses: actions/checkout@v3
      with:
        ref: ${{ matrix.branch }}
    - name: run operator-tool bump-bugfix
      run: |
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        make components/bump-bugfix
    - name: create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Bump payloads versions
        committer: Vincent Demeester <vdemeest@redhat.com>
        author: Vincent Demeester <vdemeest@redhat.com>
        signoff: true
        # author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: bot-bump-payload-${{ matrix.branch }}
        delete-branch: true
        title: "[bot] bump payload versions"
        labels: |
          release-note-none
