name: Bump components.yaml on release branches

on:  # yamllint disable-line rule:truthy
  workflow_dispatch: {}
  schedule:
  # Run this every week day at 2AM
  - cron: '0 2 * * 1-5'

jobs:
  build-release-matrix:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'tektoncd'  # do not run this elsewhere
    steps:
    - id: set-matrix
      run: |
        SUPPORTED_BRANCHES=$(git ls-remote --heads https://github.com/tektoncd/operator 'release-*' | grep -v 'v0.2[0-9].*\|v0.5[0-9]\.*\|v0.6[0-7]\.*' | awk '{ print $2 }' | cut -d/ -f3- | jq -cRs 'split("\n")[:-1]')
        echo "Supported Branches: ${SUPPORTED_BRANCHES}"
        echo "branches=${SUPPORTED_BRANCHES}" >> $GITHUB_OUTPUT
    outputs:
      branches: ${{ steps.set-matrix.outputs.branches }}
  bump-payloads:
    needs: build-release-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.build-release-matrix.outputs.branches) }}
        # branch: [release-v0.62.x, release-v0.63.x]
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        ref: ${{ matrix.branch }}
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: "go.mod"
    - name: run operator-tool bump-bugfix
      run: |
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        make components/bump-bugfix
    - name: create pull request
      uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
      with:
        token: ${{ secrets.TEKTON_BOT_TOKEN }}
        commit-message: Bump payloads versions
        committer: tekton-bot <tekton-bot@users.noreply.github.com>
        author: Vincent Demeester <vdemeest@redhat.com>
        signoff: true
        # author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: bot-bump-payload-${{ matrix.branch }}
        delete-branch: true
        title: "[bot] bump payload versions"
        labels: |
          release-note-none
